"""Create clan table

Revision ID: 3354f8920788
Revises: de4a9a5caa3f
Create Date: 2025-02-20 10:17:00.282071

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "3354f8920788"
down_revision: Union[str, None] = "de4a9a5caa3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clan",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_clan_id"), "clan", ["id"], unique=False)
    op.create_table(
        "clanwarehouse",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("clan_id", sa.Uuid(), nullable=False),
        sa.Column("resources", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["clan_id"],
            ["clan.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("clan_id"),
    )
    op.create_index(op.f("ix_clanwarehouse_id"), "clanwarehouse", ["id"], unique=False)

    op.add_column("user", sa.Column("clan_id", sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, "user", ["clan_id"])
    op.create_foreign_key(None, "user", "clan", ["clan_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "clan_id")
    op.drop_index(op.f("ix_clanwarehouse_id"), table_name="clanwarehouse")
    op.drop_table("clanwarehouse")
    op.drop_index(op.f("ix_clan_id"), table_name="clan")
    op.drop_table("clan")
    # ### end Alembic commands ###
