"""Update resources model

Revision ID: a629916f89c1
Revises: 3354f8920788
Create Date: 2025-02-22 12:38:07.231941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel #added


# revision identifiers, used by Alembic.
revision: str = 'a629916f89c1'
down_revision: Union[str, None] = '3354f8920788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('base_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'base_price')
    # ### end Alembic commands ###
