"""Create missions table

Revision ID: 42ea33e7398c
Revises: 9ecb24bd9ebf
Create Date: 2025-03-02 16:39:53.279938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel #added


# revision identifiers, used by Alembic.
revision: str = '42ea33e7398c'
down_revision: Union[str, None] = '9ecb24bd9ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('reward_money', sa.Integer(), nullable=False),
    sa.Column('reward_exp', sa.Integer(), nullable=False),
    sa.Column('reward_luck', sa.Integer(), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('max_champions', sa.Integer(), nullable=False),
    sa.Column('min_champions', sa.Integer(), nullable=False),
    sa.Column('max_items', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['clan_id'], ['clan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_mission_id'), 'mission', ['id'], unique=False)
    op.add_column('champion', sa.Column('clan_id', sa.Uuid(), nullable=True))
    op.add_column('champion', sa.Column('mission_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'champion', 'clan', ['clan_id'], ['id'])
    op.create_foreign_key(None, 'champion', 'mission', ['mission_id'], ['id'])
    op.add_column('item', sa.Column('clan_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'item', 'clan', ['clan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'clan_id')
    op.drop_constraint(None, 'champion', type_='foreignkey')
    op.drop_constraint(None, 'champion', type_='foreignkey')
    op.drop_column('champion', 'mission_id')
    op.drop_column('champion', 'clan_id')
    op.drop_index(op.f('ix_mission_id'), table_name='mission')
    op.drop_table('mission')
    # ### end Alembic commands ###
