"""Create players table

Revision ID: e9e3aff3e9ba
Revises: 
Create Date: 2025-02-17 14:20:55.537418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel #added


# revision identifiers, used by Alembic.
revision: str = 'e9e3aff3e9ba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
