"""Create clan table

Revision ID: 3354f8920788
Revises: de4a9a5caa3f
Create Date: 2025-02-20 10:17:00.282071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel #added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3354f8920788'
down_revision: Union[str, None] = 'de4a9a5caa3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_clan_id'), 'clan', ['id'], unique=False)
    op.create_table('clanwarehouse',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('clan_id', sa.Uuid(), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clan.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clan_id')
    )
    op.create_index(op.f('ix_clanwarehouse_id'), 'clanwarehouse', ['id'], unique=False)
    op.drop_index('ix_artefact_id', table_name='artefact')
    op.drop_table('artefact')
    op.add_column('item', sa.Column('power', sa.Integer(), nullable=False))
    op.add_column('item', sa.Column('quality', sa.Enum('common', 'uncommon', 'rare', 'epic', 'magnificent', 'legendary', 'artefact', name='itemquality'), nullable=False))
    op.drop_constraint('item_secondary_resource_id_fkey', 'item', type_='foreignkey')
    op.drop_constraint('item_parent_id_fkey', 'item', type_='foreignkey')
    op.drop_constraint('item_main_resource_id_fkey', 'item', type_='foreignkey')
    op.drop_column('item', 'parent_id')
    op.drop_column('item', 'secondary_resource_id')
    op.drop_column('item', 'main_resource_id')
    op.add_column('resource', sa.Column('item_type', sa.Enum('resource', 'weapon', 'armor', 'potion', 'scroll', 'ring', 'amulet', 'rod', 'wand', 'staff', 'orb', 'tome', 'grimoire', 'talisman', name='itemtype'), nullable=False))
    op.add_column('resource', sa.Column('recipe', sa.JSON(), nullable=True))
    op.add_column('user', sa.Column('clan_id', sa.Uuid(), nullable=True))
    op.create_unique_constraint(None, 'user', ['clan_id'])
    op.create_foreign_key(None, 'user', 'clan', ['clan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'clan_id')
    op.drop_column('resource', 'recipe')
    op.drop_column('resource', 'item_type')
    op.add_column('item', sa.Column('main_resource_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('secondary_resource_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('item_main_resource_id_fkey', 'item', 'resource', ['main_resource_id'], ['id'])
    op.create_foreign_key('item_parent_id_fkey', 'item', 'item', ['parent_id'], ['id'])
    op.create_foreign_key('item_secondary_resource_id_fkey', 'item', 'resource', ['secondary_resource_id'], ['id'])
    op.drop_column('item', 'quality')
    op.drop_column('item', 'power')
    op.create_table('artefact',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('power', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('weapon', 'armor', 'potion', 'scroll', 'ring', 'amulet', 'rod', 'wand', 'staff', 'orb', 'tome', 'grimoire', 'talisman', name='itemtype'), autoincrement=False, nullable=False),
    sa.Column('quality', postgresql.ENUM('common', 'uncommon', 'rare', 'epic', 'magnificent', 'legendary', name='itemquality'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='artefact_pkey'),
    sa.UniqueConstraint('name', name='artefact_name_key')
    )
    op.create_index('ix_artefact_id', 'artefact', ['id'], unique=False)
    op.drop_index(op.f('ix_clanwarehouse_id'), table_name='clanwarehouse')
    op.drop_table('clanwarehouse')
    op.drop_index(op.f('ix_clan_id'), table_name='clan')
    op.drop_table('clan')
    # ### end Alembic commands ###
