"""resources

Revision ID: 0892e2dd8cd1
Revises: 9cae7a30822c
Create Date: 2025-02-17 23:27:32.318032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel #added


# revision identifiers, used by Alembic.
revision: str = '0892e2dd8cd1'
down_revision: Union[str, None] = '9cae7a30822c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artefact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('power', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('weapon', 'armor', 'potion', 'scroll', 'ring', 'amulet', 'rod', 'wand', 'staff', 'orb', 'tome', 'grimoire', 'talisman', name='itemtype'), nullable=False),
    sa.Column('quality', sa.Enum('common', 'uncommon', 'rare', 'epic', 'magnificent', 'legendary', name='itemquality'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_artefact_id'), 'artefact', ['id'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_resource_id'), 'resource', ['id'], unique=False)
    op.create_table('item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('type', sa.Enum('weapon', 'armor', 'potion', 'scroll', 'ring', 'amulet', 'rod', 'wand', 'staff', 'orb', 'tome', 'grimoire', 'talisman', name='itemtype'), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('main_resource_id', sa.Uuid(), nullable=True),
    sa.Column('secondary_resource_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['main_resource_id'], ['resource.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['secondary_resource_id'], ['resource.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_item_id'), 'item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_resource_id'), table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_artefact_id'), table_name='artefact')
    op.drop_table('artefact')
    # ### end Alembic commands ###
